version: '3'
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  product_service:
    build: .
    depends_on:
      - kafka
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: product_service.py

  inventory_service:
    build: .
    depends_on:
      - kafka
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: inventory_service.py

  order_service:
    build: .
    depends_on:
      - kafka
    ports:
      - "5003:5003"
    environment:
      FLASK_APP: order_service.py

  notification_service:
    build: .
    depends_on:
      - kafka
    ports:
      - "5004:5004"
    environment:
      FLASK_APP: notification_service.py
